# Generated by Django 4.1.2 on 2023-01-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=250)),
                ('cfname', models.CharField(max_length=250)),
                ('ccourse', models.CharField(max_length=250)),
                ('cphone', models.CharField(max_length=15)),
            ],
        ),
    ]
